FROM ubuntu:24.04 as builder

# build phase
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV NODE_OPTIONS="--openssl-legacy-provider"

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends tzdata && \
    apt-get install -y --no-install-recommends curl sudo && \
    apt-get install -y --no-install-recommends libevent-dev libcurl4-openssl-dev libglib2.0-dev uuid-dev intltool && \
    apt-get install -y --no-install-recommends libsqlite3-dev libmysqlclient-dev libarchive-dev libtool libjansson-dev valac libfuse-dev && \
    apt-get install -y --no-install-recommends cmake re2c flex sqlite3 git libssl-dev libonig-dev libldap2-dev ldap-utils && \
    apt-get install -y --no-install-recommends gcc autoconf automake mysql-client librados-dev libxml2-dev telnet && \
    apt-get install -y --no-install-recommends libhiredis-dev libargon2-dev netbase ca-certificates apt-transport-https build-essential libxslt1-dev libffi-dev && \
    apt-get install -y --no-install-recommends libpcre3-dev zlib1g-dev xz-utils pkg-config poppler-utils libmemcached-dev libjwt-dev && \
    apt-get install -y --no-install-recommends libsasl2-dev slapd tox lcov valgrind && \
    apt-get install -y --no-install-recommends libpq-dev postgresql-client && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root/dev/source-code
RUN git config --global http.sslverify false && \
    git config --global https.sslverify false && \
    git clone https://github.com/haiwen/libevhtp.git /root/dev/source-code/libevhtp && \
    git clone https://github.com/haiwen/libsearpc.git /root/dev/source-code/libsearpc && \
    git clone https://github.com/beclab/seafile-server.git /root/dev/source-code/seafile-server

WORKDIR libevhtp
RUN cmake -DEVHTP_DISABLE_SSL=ON -DEVHTP_BUILD_SHARED=OFF . && make && sudo make install && sudo ldconfig

WORKDIR ../libsearpc
RUN ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig

WORKDIR ../seafile-server
RUN git checkout fix/search_500 && ./autogen.sh && ./configure --disable-fuse && make && sudo make install && sudo ldconfig && rm -rf /root/dev/source-code

WORKDIR /root/dev/source-code/seafile-server
COPY . ./


FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

# final image
RUN apt-get -y update && \
    apt-get install -y --no-install-recommends libevent-dev sudo libglib2.0-dev libjansson-dev libarchive-dev && \
    apt-get install -y --no-install-recommends libhiredis-dev libargon2-dev libcurl4-openssl-dev libjwt-dev && \
    apt-get install -y --no-install-recommends libmysqlclient-dev libpq-dev && \
    apt-get install -y --no-install-recommends postgresql-client && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY --from=builder /usr/local/lib/ /usr/local/lib/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /root/dev/source-code/seafile-server/docker_seafile_server.sh /root/dev/source-code/seafile-server/docker_seafile_server.sh

WORKDIR /root/dev/source-code/seafile-server

RUN sudo ldconfig

RUN chmod +x ./docker_seafile_server.sh

EXPOSE 8082

ENTRYPOINT ["./docker_seafile_server.sh"]